---
- hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Clone Virtual Machine
      vmware_guest:
        hostname: 192.168.43.30
        username: Administrator@zconsulting.local
        password: Azerty@123456789
        validate_certs: False
        name: Web server
        folder: vm
        datacenter: Zconsulting
        esxi_hostname: 192.168.43.29
        template: "VM-centos7"
        state: poweredon
