# sample playbook to copy a file
#
-
  name: Copy files on remote servers part of group1
  hosts: 192.168.134.151
  tasks:
    -
      name: copy the war file to the prod
      copy:
        src:  /var/lib/jenkins/workspace/Job-pipeline-1/target/employee-producer-0.0.1-SNAPSHOT.war
        dest: /usr/local/apache-tomcat-7.0.76/webapps/employee-producer-0.0.1-SNAPSHOT.war
        force: yes
~
